extproc ksh .\/mkdefs.cmd 
shift 
#Generated by makefile.os2. Do not edit! 


sed -n -e '/^BEGIN_INSTALL_BUILTIN/{
  : loop
  N
  /END_INSTALL_BUILTIN/b done
  b loop
  : done
  s/BEGIN_INSTALL_BUILTIN//
  s/END_INSTALL_BUILTIN//
  p
}'
